services:
  node1:
    container_name: node1
    image: redis
    hostname: node1
    ports:
      - 7000:7000
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-network
    restart: always

  node2:
    container_name: node2
    image: redis
    hostname: node2
    ports:
      - 7001:7001
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-network
    restart: always

  node3:
    container_name: node3
    image: redis
    hostname: node3
    ports:
      - 7002:7002
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    networks:
      - redis-network
    restart: always

networks:
  redis-network:
    name: redis-network
    driver: bridge
