services:
  node1:
    container_name: node1
    image: redis:latest
    hostname: node1
    ports:
      - 7000:7000
    volumes:
      - ./node1.conf:/node1.conf
    command: redis-server /node1.conf
    networks:
      - redis-network

  node2:
    container_name: node2
    image: redis:latest
    hostname: node2
    ports:
      - 7001:7001
    volumes:
      - ./node2.conf:/node2.conf
    command: redis-server /node2.conf
    networks:
      - redis-network

  node3:
    container_name: node3
    image: redis:latest
    hostname: node3
    ports:
      - 7002:7002
    volumes:
      - ./node3.conf:/node3.conf
    command: redis-server /node3.conf
    networks:
      - redis-network

  cluster-creator:
    container_name: cluster-creator
    image: redis:latest
    ports:
      - 6999:6999
    networks:
      - redis-network
    command: redis-cli -p 7000 --cluster create node1:7000 node2:7001 node3:7002 --cluster-replicas 1 --cluster-yes
    depends_on:
      - node1
      - node2
      - node3

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight
    ports:
      - 8001:8001
    networks:
      - redis-network
    volumes:
      - ./redisinsight:/db
    depends_on:
      - cluster-creator

networks:
  redis-network:
    name: redis-network
    driver: bridge
